//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Valve.VR
{
    using System;
    using UnityEngine;
    
    
    public class SteamVR_Input_ActionSet_AudioTrip : Valve.VR.SteamVR_ActionSet
    {
        
        public virtual SteamVR_Action_Vector2 axis_2d_1
        {
            get
            {
                return SteamVR_Actions.audioTrip_axis_2d_1;
            }
        }
        
        public virtual SteamVR_Action_Vector2 axis_2d_2
        {
            get
            {
                return SteamVR_Actions.audioTrip_axis_2d_2;
            }
        }
        
        public virtual SteamVR_Action_Boolean axis_2d_1_click
        {
            get
            {
                return SteamVR_Actions.audioTrip_axis_2d_1_click;
            }
        }
        
        public virtual SteamVR_Action_Single trigger
        {
            get
            {
                return SteamVR_Actions.audioTrip_trigger;
            }
        }
        
        public virtual SteamVR_Action_Boolean menu
        {
            get
            {
                return SteamVR_Actions.audioTrip_menu;
            }
        }
        
        public virtual SteamVR_Action_Single grip
        {
            get
            {
                return SteamVR_Actions.audioTrip_grip;
            }
        }
        
        public virtual SteamVR_Action_Vibration Haptic
        {
            get
            {
                return SteamVR_Actions.audioTrip_Haptic;
            }
        }
    }
}
